# Generated by Django 3.2.4 on 2021-06-24 14:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sud-ouest', 'Sud Ouest'), ('bordeaux', 'Bordeaux'), ('bourgogne', 'Bourgogne'), ('val-de-loire', 'Val De Loire'), ('languedoc-roussillon', 'Languedoc Roussillon'), ('vallée-du-rhône', 'Vallée Du Rhône'), ('savoie', 'Savoie'), ('corse', 'Corse'), ('beaujolais', 'Beaujolais'), ('alsace-lorraine', 'Alsace Lorraine'), ('provence', 'Provence'), ('centre-loire', 'Centre Loire'), ('jura', 'Jura')], default='bordeaux', max_length=40)),
                ('slug', models.SlugField(max_length=40, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'unique_together': {('name', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favs_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('abouriou', 'Abouriou'), ('bourboulenc', 'Bourboulenc'), ('braucol', 'Braucol'), ('cabernet', 'Cabernet'), ('cabernet-Franc', 'Cabernet Franc'), ('cabernet-Sauvignon', 'Cabernet Sauvignon'), ('caladoc', 'Caladoc'), ('camaralet', 'Camaralet'), ('carignan', 'Carignan'), ('carignan-blanc', 'Carignan Blanc'), ('chardonnay', 'Chardonnay'), ('chenin', 'Chenin'), ('chenin-blanc', 'Chenin Blanc'), ('cinsault', 'Cinsault'), ('clairette', 'Clairette'), ('colombard', 'Colombard'), ('courbu', 'Courbu'), ('egiodola', 'Egiodola'), ('gamay', 'Gamay'), ('grenache', 'Grenache'), ('grenache-blanc', 'Grenache Blanc'), ('grenache-gris', 'Grenache Gris'), ('grenache-noir', 'Grenache Noir'), ('gros-Manseng', 'Gros Manseng'), ('loin-de-l-oeil', 'Loin De L Oeil'), ('macabeu', 'Macabeu'), ('malbec', 'Malbec'), ('marsanne', 'Marsanne'), ('marselan', 'Marselan'), ('mauzac', 'Mauzac'), ('melon-de-Bourgogne', 'Melon De Bourgogne'), ('merlot', 'Merlot'), ('mourvèdre', 'Mourvèdre'), ('muscadelle', 'Muscadelle'), ('muscat-petits-grains', 'Muscat Petits Grains'), ('negrette', 'Negrette'), ('petit-Courbu', 'Petit Courbu'), ('petit-Manseng', 'Petit Manseng'), ('petit-Verdot', 'Petit Verdot'), ('pineau-dAunis', 'Pineau D Aunis'), ('pinot-noir', 'Pinot Noir'), ('poulsard', 'Poulsard'), ('rolle', 'Rolle'), ('roussanne', 'Roussanne'), ('sauvignon', 'Sauvignon'), ('sauvignon-blanc', 'Sauvignon Blanc'), ('sauvignon-gris', 'Sauvignon Gris'), ('savagnin', 'Savagnin'), ('syrah', 'Syrah'), ('sémillon', 'Sémillon'), ('tannat', 'Tannat'), ('tressailler', 'Tressailler'), ('ugni-blanc', 'Ugni Blanc'), ('vermentino', 'Vermentino'), ('viognier', 'Viognier')], default='merlot', max_length=30)),
                ('slug', models.SlugField(max_length=30, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
                'unique_together': {('name', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Vin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Make must be greater than 5 Character')])),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('decription', models.TextField()),
                ('tips', models.CharField(max_length=141, validators=[django.core.validators.MaxLengthValidator(142, "Tips don't must be greater than 140 Character!")])),
                ('image', models.ImageField(blank=True, null=True, upload_to='vins/')),
                ('price', models.CharField(blank=True, choices=[('moins de 10', 'Moins'), ('de 10 à 20', 'Egal'), ('plus de 20', 'Plus')], default='de 10 à 20', max_length=11, null=True)),
                ('boutique', models.CharField(blank=True, max_length=141, null=True, validators=[django.core.validators.MaxLengthValidator(142, "Boutique don't must be greater than 140 Character!")])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_vins_auteur', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='vins.category')),
                ('favorites', models.ManyToManyField(related_name='favorite_vins', through='vins.Fav', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(help_text='Select a tag for this wine', related_name='tags', to='vins.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='fav',
            name='vin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vins.vin'),
        ),
        migrations.AlterUniqueTogether(
            name='fav',
            unique_together={('vin', 'user')},
        ),
    ]
