# Generated by Django 3.2.4 on 2021-06-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin',
            name='price',
            field=models.CharField(blank=True, choices=[('moins de 10', 'Moins De 10'), ('de 10 à 20', 'De 10 A 20'), ('plus de 20', 'Plus De 20')], default='de 10 à 20', max_length=11, null=True),
        ),
    ]
