# Generated by Django 3.1.12 on 2021-07-07 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vins', '0003_auto_20210628_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='vin',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
