# Generated by Django 3.1.12 on 2021-07-10 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vins', '0004_vin_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_vin_auteur', to=settings.AUTH_USER_MODEL),
        ),
    ]
