# Generated by Django 3.1.12 on 2021-08-27 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vins', '0005_auto_20210710_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin',
            name='category',
            field=models.ForeignKey(help_text='Select a Categorie for this wine', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='vins.category'),
        ),
    ]
