# Generated by Django 3.1.12 on 2021-09-20 13:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vins', '0006_auto_20210827_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_cat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='description_tag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vin',
            name='boutique',
            field=models.CharField(blank=True, max_length=141, null=True, validators=[django.core.validators.MaxLengthValidator(142, 'Boutique ne doit pas dépasser 140 lettres !')]),
        ),
        migrations.AlterField(
            model_name='vin',
            name='category',
            field=models.ForeignKey(help_text='Selectionnez une region pour ce vin.', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='vins.category'),
        ),
        migrations.AlterField(
            model_name='vin',
            name='tag',
            field=models.ManyToManyField(help_text='Selectionnez des cépages pour ce vin.', related_name='tags', to='vins.Tag'),
        ),
        migrations.AlterField(
            model_name='vin',
            name='tips',
            field=models.CharField(max_length=141, validators=[django.core.validators.MaxLengthValidator(142, 'Le conseil ne doit pas dépasser 140 lettres !')]),
        ),
        migrations.AlterField(
            model_name='vin',
            name='title',
            field=models.CharField(max_length=250, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'PLus que 3 lettres')]),
        ),
    ]
