# Generated by Django 3.1.12 on 2021-10-07 07:35

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('vins', '0007_auto_20210920_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, null=True, quality=75, size=[300, 300], upload_to='vinslv/'),
        ),
    ]
