# Generated by Django 3.1.12 on 2021-10-15 16:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vins', '0009_auto_20211011_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin',
            name='boutique',
            field=models.CharField(blank=True, max_length=141, null=True, validators=[django.core.validators.MaxLengthValidator(141, 'Boutique ne doit pas dépasser 140 caractères !')]),
        ),
        migrations.AlterField(
            model_name='vin',
            name='tips',
            field=models.CharField(max_length=141, validators=[django.core.validators.MaxLengthValidator(141, 'Le conseil ne doit pas dépasser 140 caractères !')]),
        ),
        migrations.AlterField(
            model_name='vin',
            name='title',
            field=models.CharField(max_length=250, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Le titre doit avoir plus de 3 caractères !')]),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(1, 'Commentaire doit être plus grand que 1 caractère. '), django.core.validators.MaxLengthValidator(141, 'Le commentaire ne doit pas dépasser 140 caractères !')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vins.vin')),
            ],
        ),
        migrations.AddField(
            model_name='vin',
            name='comments',
            field=models.ManyToManyField(related_name='comments_author', through='vins.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
