# Generated by Django 3.1.12 on 2021-10-18 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vins', '0010_auto_20211015_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin',
            name='comments',
            field=models.ManyToManyField(related_name='vin_comments', through='vins.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
